config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: 'admin/sidekiq', as: :sidekiq
  end

  devise_for :users, path: 'auth', controllers: {
    # omniauth_callbacks: 'auth/omniauth_callbacks',
    # sessions:           'auth/sessions',
    registrations:      'auth/registrations'
    # passwords:          'auth/passwords',
    # confirmations:      'auth/confirmations',
  }

  root to: 'stories#index'

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/x-nodeinfo2', to: 'well_known/x_nodeinfo2#show', as: :xnodeinfo2
  get '.well-known/nodeinfo', to: 'well_known/nodeinfo2#show', as: :nodeinfo2
  get 'nodeinfo/2.0', to: 'well_known/nodeinfo2#show_real', as: :nodeinfo2_real
  get 'manifest', to: 'manifest#show', as: :manifest, defaults: { format: 'application/manifest+json' }

  get 'accounts/:id', to: 'accounts/stories#hot', as: :network_account

  get :design, to: 'static#design'

  resource :account, path: '@:username' do
    root to: 'accounts/stories#hot'
    get :recent, to: 'accounts/stories#recent', as: :recent_stories

    resources :comments, only: [] do
      root to: 'accounts/comments#hot'
      get :recent, on: :collection, controller: 'accounts/comments'
    end
  end

  resource :feed, defaults: { format: 'atom' } do
    get :hot, to: 'stories#index'
  end

  get '/stories/:id', to: redirect('/posts/%{id}')

  resource :dashboard, only: [:show] do
    get :recent, on: :member
  end

  namespace :search do
    resources :posts, path: '/', only: [:index]
    resources :comments, only: [:index]
    resources :users, only: [:index]
  end

  resources :stories, path: :posts do
    get :recent, on: :collection

    resource :flag, only: %i[new create edit update]
  end

  resources :tags, param: :name, only: [] do
    resources :stories, path: '/', controller: 'tags/stories', only: [] do
      get '/', action: :hot, on: :collection
      get :recent, on: :collection
    end
  end

  resources :comments, only: [:index, :show] do
    get :recent, on: :collection

    resource :flag, only: %i[new create edit update]
  end

  resources :notifications, only: [:index] do
    get :unread, on: :collection
  end

  get '/ap/accounts/:username', to: redirect('/@%{username}')
  get '/ap/stories/:id', to: redirect('/stories/%{id}')
  get '/ap/comments/:id', to: redirect('/comments/%{id}')

  namespace :activitypub, path: :ap do
    resources :accounts, only: [], param: :username do
      get :outbox, on: :member

      resource :inbox, only: [:create], controller: 'account/inbox'
    end
  end

  namespace :api do
    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    namespace :ujs do
      namespace :markdown do
        get :preview
      end

      resources :stories, only: [] do
        post :toggle_like, on: :member
        post :scrap, on: :member
        delete :destroy, on: :member, as: :delete
      end

      resources :comments, only: [:new, :create, :edit, :update, :destroy] do
        post :toggle_like, on: :member
      end

      resources :accounts, only: [] do
        post :toggle_follow, on: :member
      end

      resources :tags, only: [] do
        post :toggle_follow, on: :member
      end
    end

    namespace :v1, defaults: { format: :json } do
      post 'tools/scrap_url', controller: :tools, action: :scrap_url

      resources :notifications, only: [] do
        get :unread_count, on: :collection
      end

      resources :tags, only: [:index]
    end
  end

  namespace :settings do
    resource :profile, only: [:show, :update, :destroy]
    resource :preferences, only: [:show, :update]
  end

  namespace :admin do
    resource :settings, only: [:edit, :update]
    resources :accounts, except: [:delete] do
      post :suspend, on: :member
      post :silence, on: :member
      post :unsilence, on: :member
    end
    resources :domain_blocks, except: [:edit, :update]
    resources :flags, except: [:new, :create, :delete] do
      post :resolve, on: :member
      post :unresolve, on: :member
    end
  end
end

app/views/shared/_flash.html.slim
.flashes(data-controller="flashes")
  - flash.each do |severity, value|
    .flashes-item(
      data-severity=severity
      data-value=value
      data-target="flashes.item"
    )

app/views/shared/_follow_btn.html.slim
a.btn.btn--sm.btn--primary(
  class=presenter.root_class
  data-controller="follow-btn"
  data-follow-btn-action-path=toggle_follow_api_ujs_account_path(presenter.account)
  data-follow-btn-following=presenter.following?.to_s
  data-follow-btn-username=presenter.account.username
  data-action="click->follow-btn#toggle"
)

  i.fe.mr--xs(class=presenter.icon_class)
  = presenter.label

app/views/shared/_footer.html.slim
footer.text--center
  p #{t('.powered_by')} <a href="https://gitlab.com/prismosuite/prismo"><span>△</span> Prismo</a> #{Prismo::Version}

app/views/shared/_head.html.slim
meta(name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no")
link(rel="apple-touch-icon" sizes="180x180" href="/ios.png")
link(id="favicon" rel="icon" href="/favicon.png" type="image/png" sizes="32x32" data-controller="favicon")
link(rel="manifest" href=manifest_path(format: :json))

meta(name="current-account-id" content=current_account&.id)
meta(name="sendry-dsn" content=ENV['SENTRY_DSN_FE'])
meta(name="local-https" content=ENV['LOCAL_HTTPS'])
meta(name="local-domain" content=ENV['LOCAL_DOMAIN'])

app/views/shared/_markdown_editor.html.slim
- placeholder ||= ''
- additional_input_targets ||= []
- additional_preview_classes ||= []
- targets = (['markdown-editor.input'] + additional_input_targets).compact.join(' ')

.markdown-editor(data-controller="markdown-editor")
  .markdown-editor__body
    .markdown-editor__body-pane.markdown-editor__body-input.active(data-target="markdown-editor.editor")
      = form.text_area name, class: 'form-control',
                             placeholder: placeholder,
                             data: { target: targets }

    .markdown-editor__body-pane.markdown-editor__body-preview.text-component(
      data-target="markdown-editor.preview"
      class=additional_preview_classes
    )
      p = t('.nothing_to_show')

  .markdown-editor__footer
    a(href="https://simplemde.com/markdown-guide" target="_blank")
      = t('.markdown_supported')

    a.float-right(href="#" data-action="markdown-editor#togglePreview")
      = t('.toggle_preview')

app/views/shared/_navbar.html+phone.slim
header.main-header
  .container
    .main-header__layout
      = render 'shared/_navbar/jumpbox'

      nav.main-header__nav
        ul.main-header__nav-list
          li.main-header__nav-item
            = active_link_to new_story_path do
              i.fe.fe-plus-circle

          li.main-header__nav-item
            = active_link_to search_posts_path do
              i.fe.fe-search

          - if user_signed_in?
            li.main-header__nav-item
              = render 'shared/_navbar/notifications'
            li.main-header__nav-item
              = render 'shared/_navbar/profile'

          - else
            li.main-header__nav-item
              = link_to new_user_session_path do
                i.fe.fe-log-in

app/views/shared/_navbar.html.slim
header.main-header
  .container
    .main-header__layout
      .main-header__logo
        = link_to Setting.site_title, root_path

      = render 'shared/_navbar/jumpbox'

      nav.main-header__nav
        ul.main-header__nav-list
          li.main-header__nav-item
            = active_link_to t('.add_story'), new_story_path

          li.main-header__nav-item
            = active_link_to search_posts_path do
              i.fe.fe-search

          - if user_signed_in?
            li.main-header__nav-item
              = render 'shared/_navbar/notifications'
            li.main-header__nav-item
              = render 'shared/_navbar/profile'

          - else
            li.main-header__nav-item
              = link_to new_user_session_path, title: t('.join_us') do
                i.fe.fe-log-in

app/views/shared/_popular_tags.html.slim
- tags = TagsQuery.new.popular.first(10).map(&:decorate)

.box.--touches-header.mb-3.popular-tags
  .box__body
    ul
      - tags.each do |tag|
        li.list-inline-item
          a(href=tag.path) ##{tag.name}

app/views/shared/_sentry.erb
<% if ENV.key?('SENTRY_DSN_FE') %>
  <script src="https://cdn.ravenjs.com/3.19.1/raven.min.js" crossorigin="anonymous"></script>
<% end %>